version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        jar_path: $JAR_PATH
    ports:
      - "8080:8080"
    networks:
      backend-network:
        ipv4_address: $BACKEND_IP
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - "${DB_PORT}:5432"
    networks:
      backend-network:
        ipv4_address: $DB_IP

networks:
  backend-network:
    ipam:
      config:
        - subnet: $SUBNET_RANGE

