version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        jar_path: $JAR_PATH
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

