CREATE TABLE flat (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(255) NOT NULL,
    surface DOUBLE PRECISION  NOT NULL,
    cost DOUBLE PRECISION NOT NULL
);

CREATE TABLE room (
    id BIGSERIAL PRIMARY KEY,
    uuid VARCHAR(255) NOT NULL,
    surface DOUBLE PRECISION NOT NULL,
    flat_id BIGINT NOT NULL,
    FOREIGN KEY (flat_id) REFERENCES flat(id)
);